# Generated by Django 3.1.5 on 2021-01-18 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0002_auto_20210119_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date',
        ),
        migrations.AddField(
            model_name='list',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
