# Generated by Django 3.1.5 on 2021-01-18 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0004_auto_20210119_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
